# config/config.yaml
server:
  port: 8080
  environment: development
  log_level: debug
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: localhost
  port: 5432
  name: hermes_dev
  user: hermes_user
  password: ${DB_PASSWORD}
  ssl_mode: disable
  max_connections: 10
  connection_timeout: 5s

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: ${RABBITMQ_PASSWORD}
  vhost: /
  connection_timeout: 30s
  heartbeat: 10s

redis:
  host: localhost
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0
  pool_size: 10

logging:
  level: debug
  format: text  # "json" for production
  output: stdout

notifications:
  default_retry_count: 3
  max_retry_count: 5
  retry_delay: 5s
  batch_size: 50
  workers: 2

security:
  jwt_secret: ${JWT_SECRET}
  bcrypt_cost: 12
  cors_origins: 
    - "http://localhost:3000"
    - "http://localhost:8080"